# Generated by Django 2.2.5 on 2019-09-21 13:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, default=100.0, max_digits=100, validators=[django.core.validators.MinValueValidator(50)])),
                ('time_required', models.TimeField()),
                ('fuel_required', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ending_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_ending_atc', to='atc.Atc')),
                ('starting_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_starting_atc', to='atc.Atc')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_time', models.DateTimeField(default=datetime.datetime.now)),
                ('expected_end', models.DateTimeField(default=datetime.datetime.now)),
                ('ending_time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ending_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_atc', to='atc.Atc')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Path')),
                ('starting_atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_atc', to='atc.Atc')),
            ],
        ),
    ]
