# Generated by Django 2.2.5 on 2019-09-21 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20190921_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='emergency_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='path',
            name='time_required',
            field=models.CharField(max_length=10),
        ),
    ]
