# Generated by Django 2.2.5 on 2019-09-21 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20190921_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='emergency_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
