# Generated by Django 2.2.5 on 2019-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_flight_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
