# Generated by Django 2.2.5 on 2019-09-21 13:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('runways', models.PositiveSmallIntegerField(default=1)),
                ('takeoff_limit', models.PositiveSmallIntegerField(default=2)),
                ('landing_limit', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user_for', models.PositiveSmallIntegerField(choices=[(0, 'TAKEOFF'), (1, 'LANDING')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atc.Atc')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=100.0, max_digits=100, validators=[django.core.validators.MinValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_atc', to='atc.Atc')),
                ('atcto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_atc', to='atc.Atc')),
            ],
        ),
    ]
