# Generated by Django 2.2.5 on 2019-09-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runway',
            old_name='status',
            new_name='is_used',
        ),
        migrations.AlterUniqueTogether(
            name='neighbour',
            unique_together={('atc', 'atcto')},
        ),
    ]
