# Generated by Django 2.2.5 on 2019-09-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0002_auto_20190921_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runway',
            old_name='user_for',
            new_name='used_for',
        ),
    ]
