# Generated by Django 2.2.5 on 2019-09-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0004_auto_20190921_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runway',
            old_name='used_for',
            new_name='use',
        ),
    ]
